# Generated by Django 4.0.3 on 2022-03-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BigDWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_text', models.CharField(max_length=50)),
                ('word_length', models.SmallIntegerField(null=True)),
                ('word_alpha', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WordleWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_text', models.CharField(max_length=50)),
            ],
        ),
    ]
