# Generated by Django 4.0.3 on 2022-05-02 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsolver', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BigDWord',
        ),
    ]
