# Generated by Django 4.0.3 on 2022-03-06 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsolver', '0002_mydictionary_delete_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordleDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_text', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='MyDictionary',
            new_name='BigDictionary',
        ),
    ]
