# Generated by Django 4.0.3 on 2022-05-02 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsolver', '0002_delete_bigdword'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WordleWord',
        ),
    ]
