# Generated by Django 4.0.3 on 2022-03-06 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsolver', '0003_wordledictionary_rename_mydictionary_bigdictionary'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_text', models.CharField(max_length=50)),
                ('score', models.SmallIntegerField(null=True)),
            ],
        ),
    ]
