# Generated by Django 4.0.3 on 2022-03-06 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsolver', '0004_validwords'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BigDictionary',
            new_name='BigDWord',
        ),
        migrations.RenameModel(
            old_name='ValidWords',
            new_name='ValidWord',
        ),
        migrations.RenameModel(
            old_name='WordleDictionary',
            new_name='WordleWord',
        ),
    ]
