# Generated by Django 4.0.3 on 2022-03-07 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsolver', '0006_delete_bigdword'),
    ]

    operations = [
        migrations.CreateModel(
            name='BigDWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_text', models.CharField(max_length=50)),
            ],
        ),
    ]
