# Generated by Django 4.0.3 on 2022-03-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsolver', '0008_validword_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigdword',
            name='word_alpha',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='bigdword',
            name='word_length',
            field=models.SmallIntegerField(null=True),
        ),
    ]
