# Generated by Django 4.0.3 on 2022-03-10 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsolver', '0009_bigdword_word_alpha_bigdword_word_length'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ValidWord',
        ),
    ]
